apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    uid: influxdb
    jsonData:
      version: Flux
      organization: home
      defaultBucket: home-iot
      tlsSkipVerify: true
      httpMode: POST
    secureJsonData:
      token: homeiot-super-secret-token
    editable: true
