#!/usr/bin/env python3
"""Build Life Explorer v3 — full health overlay + dual range slider + speed control."""
import json

with open("/tmp/explorer_v3.json") as f:
    D = json.load(f)

js_data = {
    "gps": D["gps"],
    "places": D["places"],
    "acts": D["acts"],
    "hr": D["hr"],
    "stress": D["stress"],
    "spo2": D["spo2"],
    "steps": D["steps"],
    "sleep": D["sleep"],
    "temp": D["temp"],
    "humid": D["humid"],
}

DATA_JS = json.dumps(js_data, ensure_ascii=False)

html = (
'<!DOCTYPE html>\n<html lang="ko"><head><meta charset="UTF-8">\n'
'<title>Life Explorer v3</title>\n'
'<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"/>\n'
'<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>\n'
'<script src="https://unpkg.com/leaflet.heat@0.2.0/dist/leaflet-heat.js"></script>\n'
'<script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>\n'
'<style>\n'
':root{--bg:#0d1117;--sf:#161b22;--bd:#30363d;--tx:#e6edf3;--dm:#8b949e;--ac:#58a6ff;--gn:#3fb950;--pp:#bc8cff;--or:#f0883e;--rd:#f85149}\n'
'*{margin:0;padding:0;box-sizing:border-box}\n'
'body{background:var(--bg);color:var(--tx);font-family:-apple-system,sans-serif;height:100vh;display:flex;flex-direction:column;overflow:hidden}\n'
'.ctrl{padding:8px 16px;border-bottom:1px solid var(--bd);display:flex;align-items:center;gap:12px;flex-shrink:0;flex-wrap:wrap}\n'
'.ctrl h1{font-size:15px;margin-right:8px}\n'
'.ctrl label{font-size:11px;color:var(--dm)}\n'
'.ctrl input[type=range]{width:120px;-webkit-appearance:none;background:var(--bd);height:5px;border-radius:3px;vertical-align:middle}\n'
'.ctrl input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;width:14px;height:14px;border-radius:50%;background:var(--ac);cursor:grab}\n'
'.ctrl input[type=date]{background:var(--sf);color:var(--tx);border:1px solid var(--bd);border-radius:4px;padding:2px 6px;font-size:11px}\n'
'.ctrl button{background:var(--sf);color:var(--tx);border:1px solid var(--bd);border-radius:4px;padding:3px 10px;font-size:11px;cursor:pointer}\n'
'.ctrl button.on{background:var(--ac);color:#000}\n'
'.ctrl .sep{width:1px;height:20px;background:var(--bd)}\n'
'.tbar{padding:4px 16px;border-bottom:1px solid var(--bd);display:flex;align-items:center;gap:8px;flex-shrink:0}\n'
'.tbar .tlbl{font-size:13px;font-weight:600;color:var(--ac);min-width:160px}\n'
'.tbar input[type=range]{flex:1;-webkit-appearance:none;background:var(--bd);height:6px;border-radius:3px}\n'
'.tbar input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;width:16px;height:16px;border-radius:50%;background:var(--rd);cursor:grab;box-shadow:0 0 6px var(--rd)}\n'
'.tbar .cnt{font-size:11px;color:var(--dm);min-width:80px;text-align:right}\n'
'.main{flex:1;display:flex;overflow:hidden}\n'
'#sb{width:340px;overflow-y:auto;border-right:1px solid var(--bd)}\n'
'#map{flex:1}\n'
'.panel{padding:10px 14px;border-bottom:1px solid var(--bd)}\n'
'.panel h3{font-size:11px;color:var(--ac);margin-bottom:6px}\n'
'.kpi{display:grid;grid-template-columns:repeat(4,1fr);gap:4px}\n'
'.k{background:var(--bg);border:1px solid var(--bd);border-radius:5px;padding:6px;text-align:center}\n'
'.k .v{font-size:16px;font-weight:700}\n'
'.k .l{font-size:8px;color:var(--dm);text-transform:uppercase}\n'
'#health-chart{height:200px}\n'
'#steps-chart{height:120px}\n'
'.cal{display:flex;flex-wrap:wrap;gap:1px}\n'
'.cd{width:11px;height:11px;border-radius:2px;cursor:pointer}\n'
'.cd:hover{outline:1px solid var(--tx)}\n'
'#pl{list-style:none;max-height:160px;overflow-y:auto}\n'
'#pl li{display:flex;align-items:center;gap:5px;padding:2px 0;font-size:10px;cursor:pointer;border-bottom:1px solid var(--bd)}\n'
'#pl li:hover{color:var(--ac)}\n'
'.dt{width:6px;height:6px;border-radius:50%;flex-shrink:0}\n'
'.leaflet-container{background:var(--bg)!important}\n'
'::-webkit-scrollbar{width:4px}\n'
'::-webkit-scrollbar-thumb{background:var(--bd);border-radius:2px}\n'
'</style></head><body>\n'
'<div class="ctrl">\n'
'<h1>Life Explorer</h1>\n'
'<label>FROM</label><input type="date" id="dfrom" value="2025-07-01">\n'
'<label>TO</label><input type="date" id="dto" value="2026-04-07">\n'
'<button onclick="applyRange()">적용</button>\n'
'<div class="sep"></div>\n'
'<button onclick="pb(-1)">&#9664;</button>\n'
'<button onclick="pb(0)" class="on" id="bstop">&#9208;</button>\n'
'<button onclick="pb(1)">&#9654;</button>\n'
'<button onclick="pb(3)">&#9654;&#9654;</button>\n'
'<div class="sep"></div>\n'
'<label>속도</label><input type="range" id="spd" min="1" max="50" value="10">\n'
'<span id="spdv" style="font-size:11px;color:var(--dm)">10x</span>\n'
'</div>\n'
'<div class="tbar">\n'
'<span class="tlbl" id="tl">--</span>\n'
'<input type="range" id="sl" min="0" max="100" value="100">\n'
'<span class="cnt" id="tc">--</span>\n'
'</div>\n'
'<div class="main">\n'
'<div id="sb">\n'
'<div class="panel"><h3>현재 시점 데이터</h3><div class="kpi" id="kpi"></div></div>\n'
'<div class="panel"><h3>심박수 / 스트레스</h3><div id="health-chart"></div></div>\n'
'<div class="panel"><h3>걸음수 / 수면</h3><div id="steps-chart"></div></div>\n'
'<div class="panel"><h3>Life Calendar</h3><div class="cal" id="cal"></div></div>\n'
'<div class="panel"><h3>자주 방문</h3><ul id="pl"></ul></div>\n'
'</div>\n'
'<div id="map"></div>\n'
'</div>\n'
'<script>\n'
'var D=' + DATA_JS + ';\n'
'D.gps.sort(function(a,b){return a[2]<b[2]?-1:1;});\n'
'\n'
'var map=L.map("map").setView([37.45,126.89],12);\n'
'L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{maxZoom:19}).addTo(map);\n'
'\n'
'var trail=null,heat=null,actL=null,curMk=null,ptimer=null;\n'
'var filtGps=D.gps,filtActs=D.acts;\n'
'var tc={INFERRED_HOME:"#bc8cff",INFERRED_WORK:"#58a6ff",UNKNOWN:"#3fb950"};\n'
'var ac={WALKING:"#3fb950",IN_VEHICLE:"#f0883e",CYCLING:"#d29922",RUNNING:"#f85149",IN_RAIL_VEHICLE:"#58a6ff"};\n'
'var sl=document.getElementById("sl");\n'
'var spdEl=document.getElementById("spd");\n'
'spdEl.oninput=function(){document.getElementById("spdv").textContent=this.value+"x";};\n'
'\n'
'function applyRange(){\n'
'  var f=document.getElementById("dfrom").value+"T00:00:00";\n'
'  var t=document.getElementById("dto").value+"T23:59:59";\n'
'  filtGps=D.gps.filter(function(p){return p[2]>=f&&p[2]<=t;});\n'
'  filtActs=D.acts.filter(function(a){return a.t>=f&&a.t<=t;});\n'
'  sl.max=Math.max(1,filtGps.length-1);\n'
'  sl.value=filtGps.length-1;\n'
'  draw(filtGps.length-1);\n'
'  updateCharts(f.slice(0,10),t.slice(0,10));\n'
'  if(filtGps.length>1){\n'
'    var bl=filtGps.map(function(p){return[p[0],p[1]];});\n'
'    map.fitBounds(bl,{padding:[30,30]});\n'
'  }\n'
'}\n'
'\n'
'function draw(idx){\n'
'  if(idx<0)idx=0;\n'
'  if(idx>=filtGps.length)idx=filtGps.length-1;\n'
'  var pts=filtGps.slice(0,idx+1);\n'
'  var ll=pts.map(function(p){return[p[0],p[1]];});\n'
'  if(trail)map.removeLayer(trail);\n'
'  trail=L.polyline(ll,{color:"#58a6ff",weight:2.5,opacity:0.6}).addTo(map);\n'
'  if(curMk)map.removeLayer(curMk);\n'
'  if(pts.length>0){\n'
'    var last=pts[pts.length-1];\n'
'    curMk=L.circleMarker([last[0],last[1]],{radius:7,color:"#fff",fillColor:"#f85149",fillOpacity:1,weight:2}).addTo(map);\n'
'    document.getElementById("tl").textContent=last[2].replace("T"," ");\n'
'    document.getElementById("tc").textContent=pts.length+"/"+filtGps.length;\n'
'    updateKPI(last[2].slice(0,10));\n'
'  }\n'
'  if(heat)map.removeLayer(heat);\n'
'  var step=Math.max(1,Math.floor(pts.length/1500));\n'
'  var hp=[];for(var i=0;i<pts.length;i+=step)hp.push([pts[i][0],pts[i][1],0.4]);\n'
'  heat=L.heatLayer(hp,{radius:12,blur:18,maxZoom:14}).addTo(map);\n'
'  if(actL)map.removeLayer(actL);\n'
'  var cutoff=pts.length>0?pts[pts.length-1][2]:"";\n'
'  actL=L.layerGroup();\n'
'  for(var i=0;i<filtActs.length;i++){\n'
'    var a=filtActs[i];\n'
'    if(a.t<=cutoff&&a.sl){\n'
'      L.polyline([[a.sl,a.so],[a.el,a.eo]],{color:ac[a.ty]||"#8b949e",weight:3,opacity:0.7}).addTo(actL);\n'
'    }\n'
'  }\n'
'  actL.addTo(map);\n'
'}\n'
'\n'
'function updateKPI(dateStr){\n'
'  var hr=D.hr[dateStr]||"--";\n'
'  var st=D.stress[dateStr]||"--";\n'
'  var sp=D.spo2[dateStr]||"--";\n'
'  var stp=D.steps[dateStr]||"--";\n'
'  var slp=D.sleep[dateStr]||"--";\n'
'  var tmp=D.temp[dateStr]||"--";\n'
'  var hmd=D.humid[dateStr]||"--";\n'
'  var stpFmt=(typeof stp==="number")?stp.toLocaleString():stp;\n'
'  document.getElementById("kpi").innerHTML=\n'
'    "<div class=\\"k\\"><div class=\\"v\\" style=\\"color:var(--rd)\\">"+hr+"</div><div class=\\"l\\">심박bpm</div></div>"+\n'
'    "<div class=\\"k\\"><div class=\\"v\\" style=\\"color:var(--or)\\">"+st+"</div><div class=\\"l\\">스트레스</div></div>"+\n'
'    "<div class=\\"k\\"><div class=\\"v\\" style=\\"color:var(--ac)\\">"+sp+"</div><div class=\\"l\\">SpO2%</div></div>"+\n'
'    "<div class=\\"k\\"><div class=\\"v\\" style=\\"color:var(--gn)\\">"+stpFmt+"</div><div class=\\"l\\">걸음</div></div>"+\n'
'    "<div class=\\"k\\"><div class=\\"v\\" style=\\"color:var(--pp)\\">"+slp+"</div><div class=\\"l\\">수면h</div></div>"+\n'
'    "<div class=\\"k\\"><div class=\\"v\\" style=\\"color:var(--ac)\\">"+tmp+"</div><div class=\\"l\\">온도°C</div></div>"+\n'
'    "<div class=\\"k\\"><div class=\\"v\\" style=\\"color:var(--ac)\\">"+hmd+"</div><div class=\\"l\\">습도%</div></div>"+\n'
'    "<div class=\\"k\\"><div class=\\"v\\" style=\\"color:var(--dm)\\">"+dateStr.slice(5)+"</div><div class=\\"l\\">날짜</div></div>";\n'
'}\n'
'\n'
'function updateCharts(from,to){\n'
'  var days=Object.keys(D.hr).filter(function(d){return d>=from&&d<=to;}).sort();\n'
'  var days2=Object.keys(D.steps).filter(function(d){return d>=from&&d<=to;}).sort();\n'
'  var hrV=days.map(function(d){return D.hr[d]||null;});\n'
'  var stV=days.map(function(d){return D.stress[d]||null;});\n'
'  var spV=days.map(function(d){return D.spo2[d]||null;});\n'
'  var stpV=days2.map(function(d){return D.steps[d]||0;});\n'
'  var slV=days2.map(function(d){return D.sleep[d]||0;});\n'
'  Plotly.newPlot("health-chart",[\n'
'    {x:days,y:hrV,name:"심박",type:"scatter",mode:"lines",line:{color:"#f85149",width:1.5}},\n'
'    {x:days,y:stV,name:"스트레스",type:"scatter",mode:"lines",line:{color:"#f0883e",width:1.5},yaxis:"y2"},\n'
'    {x:days,y:spV,name:"SpO2",type:"scatter",mode:"lines",line:{color:"#58a6ff",width:1},yaxis:"y3"}\n'
'  ],{paper_bgcolor:"transparent",plot_bgcolor:"transparent",font:{color:"#e6edf3",size:9},\n'
'    margin:{t:5,r:40,b:25,l:35},showlegend:true,legend:{x:0,y:1.15,orientation:"h",font:{size:9}},\n'
'    xaxis:{gridcolor:"#30363d",tickangle:-45},\n'
'    yaxis:{title:"bpm",gridcolor:"#30363d",side:"left"},\n'
'    yaxis2:{overlaying:"y",side:"right",showgrid:false},\n'
'    yaxis3:{overlaying:"y",side:"right",showgrid:false,visible:false}\n'
'  },{responsive:true,displayModeBar:false});\n'
'  Plotly.newPlot("steps-chart",[\n'
'    {x:days2,y:stpV,name:"걸음",type:"bar",marker:{color:"#3fb950",opacity:0.7}},\n'
'    {x:days2,y:slV.map(function(v){return v*1000;}),name:"수면(x1000)",type:"scatter",mode:"lines",line:{color:"#bc8cff",width:2},yaxis:"y2"}\n'
'  ],{paper_bgcolor:"transparent",plot_bgcolor:"transparent",font:{color:"#e6edf3",size:9},\n'
'    margin:{t:5,r:30,b:25,l:40},barmode:"overlay",showlegend:true,legend:{x:0,y:1.15,orientation:"h",font:{size:9}},\n'
'    xaxis:{gridcolor:"#30363d",tickangle:-45},\n'
'    yaxis:{gridcolor:"#30363d"},\n'
'    yaxis2:{overlaying:"y",side:"right",showgrid:false}\n'
'  },{responsive:true,displayModeBar:false});\n'
'}\n'
'\n'
'var raf=null;\n'
'sl.addEventListener("input",function(){\n'
'  if(raf)cancelAnimationFrame(raf);\n'
'  raf=requestAnimationFrame(function(){draw(parseInt(sl.value));});\n'
'});\n'
'\n'
'function pb(s){\n'
'  if(ptimer){clearInterval(ptimer);ptimer=null;}\n'
'  document.querySelectorAll(".ctrl button").forEach(function(b){b.classList.remove("on");});\n'
'  if(s===0){document.getElementById("bstop").classList.add("on");return;}\n'
'  var speed=parseInt(spdEl.value);\n'
'  var step=s>0?Math.max(1,s*speed):-speed;\n'
'  ptimer=setInterval(function(){\n'
'    var v=parseInt(sl.value)+step;\n'
'    if(v>=filtGps.length){v=filtGps.length-1;clearInterval(ptimer);}\n'
'    if(v<0){v=0;clearInterval(ptimer);}\n'
'    sl.value=v;draw(v);\n'
'  },50);\n'
'}\n'
'\n'
'// Places\n'
'var mkL=L.layerGroup();\n'
'for(var i=0;i<D.places.length;i++){\n'
'  var p=D.places[i];\n'
'  var c=tc[p.t]||"#3fb950";\n'
'  var sz=Math.min(18,8+p.v/10);\n'
'  var icon=L.divIcon({className:"",html:"<div style=\\"width:"+sz+"px;height:"+sz+"px;background:"+c+";border-radius:50%;border:2px solid #fff;box-shadow:0 0 6px "+c+"\\"></div>",iconSize:[sz,sz],iconAnchor:[sz/2,sz/2]});\n'
'  L.marker([p.lat,p.lon],{icon:icon}).addTo(mkL).bindPopup("<b>#"+p.r+" "+p.name+"</b><br>"+p.v+"회 "+Math.round(p.avg)+"분/회 "+p.th+"h");\n'
'}\n'
'mkL.addTo(map);\n'
'var plEl=document.getElementById("pl");\n'
'for(var i=0;i<D.places.length;i++){\n'
'  var p=D.places[i];var c=tc[p.t]||"#3fb950";\n'
'  var li=document.createElement("li");\n'
'  li.innerHTML="<span class=\\"dt\\" style=\\"background:"+c+"\\"></span><span style=\\"flex:1\\">"+p.name+"</span><span style=\\"color:var(--gn)\\">"+p.v+"</span>";\n'
'  (function(pp){li.onclick=function(){map.setView([pp.lat,pp.lon],15);};})(p);\n'
'  plEl.appendChild(li);\n'
'}\n'
'\n'
'// Calendar\n'
'var allD=Object.keys(D.steps).sort();\n'
'var mx=Math.max.apply(null,allD.map(function(d){return D.steps[d]||0;}))||1;\n'
'var calEl=document.getElementById("cal");\n'
'for(var i=0;i<allD.length;i++){\n'
'  var d=allD[i],v=D.steps[d]||0,r=v/mx;\n'
'  var c=r>0.7?"#3fb950":r>0.4?"#2ea043":r>0.1?"#1a7f37":"#161b22";\n'
'  var div=document.createElement("div");div.className="cd";div.style.background=c;\n'
'  div.title=d.slice(5)+" "+v.toLocaleString()+" steps";\n'
'  (function(dd){div.onclick=function(){\n'
'    document.getElementById("dfrom").value=dd;\n'
'    document.getElementById("dto").value=dd;\n'
'    applyRange();\n'
'  };})(d);\n'
'  calEl.appendChild(div);\n'
'}\n'
'\n'
'// Init\n'
'applyRange();\n'
'</script></body></html>\n'
)

out = "/mnt/c/Users/upica/Downloads/home-iot-life-explorer.html"
with open(out, "w", encoding="utf-8") as f:
    f.write(html)
print("OK: " + out + " (" + str(len(html)//1024) + "KB)")
